# Generated by Django 4.0.4 on 2022-04-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_session', models.DateField(blank=True, null=True, verbose_name='Date Of')),
                ('twelve_to_one', models.BooleanField()),
            ],
        ),
    ]
