# Generated by Django 4.0.4 on 2022-04-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='one_to_two',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='three_to_four',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='two_to_three',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='twelve_to_one',
            field=models.BooleanField(default=True),
        ),
    ]
